sudo: required

#branches:
#  only:
#    - master

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.21.1
  COMMIT: ${TRAVIS_COMMIT::8}
  MAIN_REPO: https://github.com/opcodio/codecheck.git
  USERS: codecheck-users
  USERS_REPO: ${MAIN_REPO}#${TRAVIS_BRANCH}:services/users
  USERS_DB: codecheck-users_db
  USERS_DB_REPO: ${MAIN_REPO}#${TRAVIS_BRANCH}:services/users/project/db
  WEB: codecheck-web
  WEB_REPO: ${MAIN_REPO}#${TRAVIS_BRANCH}:services/web
  SWAGGER: codecheck-swagger
  SWAGGER_REPO: ${MAIN_REPO}#${TRAVIS_BRANCH}:services/swagger
  SECRET_KEY: dev_secret
  

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - export REACT_APP_USERS_SERVICE_URL=http://127.0.0.1
  - yarn install

script:
 # - bash ./test.sh
  - bash ./docker-push.sh
