version: '3.6'

services:

  users:
    build:
      context: https://github.com/opcodio/codecheck-users.git
      dockerfile: Dockerfile-dev
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.TestingConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=dev_secret
    depends_on:
      - users-db
    expose:
      - '5000'
  
  users-db:
    build:
      context: https://github.com/opcodio/codecheck-users.git#master:project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - web

  web:
    build:
      context: https://github.com/opcodio/codecheck-web.git
      dockerfile: Dockerfile-dev
    ports:
      - 3007:3000
    environment:
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - users