version: '3.6'

services:

  users:
    build:
      context: ../codecheck-users
      dockerfile: Dockerfile-dev
    volumes:
      - '../codecheck-users:/usr/src/codecheck/users'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=dev_secret
    depends_on:
      - users-db
  
  users-db:
    build:
      context: ../codecheck-users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - web

  web:
    build:
      context: ../codecheck-web
      dockerfile: Dockerfile-dev
    volumes:
      - '../codecheck-web:/usr/src/codecheck/web'
      - '/usr/src/codecheck/web/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - users