version: '3.6'

services:

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db
  
  users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  exercises:
    build:
      context: ./services/exercises
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@exercises-db:5432/users_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@exercises-db:5432/users_test
    depends_on:
      - users
      - exercises-db
  
  exercises-db:
    build:
      context: ./services/exercises/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  scores:
    build:
      context: ./services/scores
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@scores-db:5432/scores_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@scores-db:5432/scores_test
      - USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
      - EXERCISES_SERVICE_URL=${REACT_APP_EXERCISES_SERVICE_URL}
    depends_on:
      - users
      - scores-db
      - exercises
  
  scores-db:
    build:
      context: ./services/scores/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
        - REACT_APP_API_GATEWAY_URL=${REACT_APP_API_GATEWAY_URL}
        - REACT_APP_EXERCISES_SERVICE_URL=${REACT_APP_EXERCISES_SERVICE_URL}
        - REACT_APP_SCORES_SERVICE_URL=${REACT_APP_SCORES_SERVICE_URL}
    expose:
      - 80
    depends_on:
      - users

  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile-prod
    expose:
      - 8080
    environment:
      - URL=swagger.json
    depends_on:
      - users

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - web
